import { relations } from "drizzle-orm";
import { pgTable, text, timestamp, boolean, uuid, index, pgEnum } from "drizzle-orm/pg-core";
import { user } from "./auth-schema";
import { updatedAndCreatedAt } from "../timestampable";

export const enrollementStatus = ["pending", "enrolled", "revoked", "unenrolled"] as const;

export const enrolmentStatusEnum = pgEnum("enrollement_status", enrollementStatus);

/**
 * Single-use device enrollment token. Generated by an authenticated admin,
 * embedded (as an opaque secret) in the Device Owner provisioning QR and
 * consumed once by POST /api/v1/devices/enroll. Mono-tenant MVP: no tenant_id.
 */
export const enrollmentTokens = pgTable(
    "enrollment_tokens",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        token: text("token").notNull().unique(),
        expiresAt: timestamp("expires_at").notNull(),
        consumedAt: timestamp("consumed_at"),
        ...updatedAndCreatedAt,
    },
    (table) => [
        index("enrollment_token_idx").on(table.token),
    ],
);

/**
 * A device enrolled via a token. Holds the identity reported at enrollment and
 * is the `sub` of the long-lived device JWT (deviceToken).
 */
export const devices = pgTable("devices", {
    id: uuid("id").primaryKey().defaultRandom(),
    enrollmentId: uuid("enrollment_id").references(() => enrollmentTokens.id, {
        onDelete: "set null",
    }),
    serial: text("serial"),
    androidId: text("android_id").unique(),
    model: text("model"),
    manufacturer: text("manufacturer"),
    osVersion: text("os_version"),
    imei: text("imei"),
    macAddress: text("mac_address"),
    ipAddress: text("ip_address"),
    status: enrolmentStatusEnum("status").default("pending").notNull(),
    lastHeartbeatAt: timestamp("last_heartbeat_at"),
    ...updatedAndCreatedAt,
});



export const deviceRelations = relations(devices, ({ one }) => ({
    enrollment: one(enrollmentTokens, {
        fields: [devices.enrollmentId],
        references: [enrollmentTokens.id],
    }),
}));
