import { relations } from "drizzle-orm";
import { pgTable, text, timestamp, boolean, uuid, index } from "drizzle-orm/pg-core";
import { user } from "./auth-schema";
import { updatedAndCreatedAt } from "../timestampable";

/**
 * Single-use device enrollment token. Generated by an authenticated admin,
 * embedded (as an opaque secret) in the Device Owner provisioning QR and
 * consumed once by POST /api/v1/devices/enroll. Mono-tenant MVP: no tenant_id.
 */
export const enrollmentTokens = pgTable(
    "enrollment_tokens",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        token: text("token").notNull().unique(),
        // Short, human-typable code (no ambiguous chars) mapping to the same row,
        // for camera-free enrollment. Stored normalized (uppercase, no separators).
        code: text("code").unique(),
        createdBy: text("created_by").references(() => user.id, { onDelete: "set null" }),
        expiresAt: timestamp("expires_at").notNull(),
        isUsed: boolean("is_used").notNull().default(false),
        usedAt: timestamp("used_at"),
        deviceId: uuid("device_id").references(() => devices.id, { onDelete: "set null" }),
        qrFileName: text("qr_file_name"),
        ...updatedAndCreatedAt,
    },
    (table) => [
        index("enrollment_tokens_token_idx").on(table.token),
        index("enrollment_tokens_code_idx").on(table.code),
    ],
);

/**
 * A device enrolled via a token. Holds the identity reported at enrollment and
 * is the `sub` of the long-lived device JWT (deviceToken).
 */
export const devices = pgTable("devices", {
    id: uuid("id").primaryKey().defaultRandom(),
    enrollmentTokenId: uuid("enrollment_token_id").references(() => enrollmentTokens.id, {
        onDelete: "set null",
    }),
    serial: text("serial"),
    model: text("model"),
    manufacturer: text("manufacturer"),
    osVersion: text("os_version"),
    status: text("status").notNull().default("enrolled"), // enrolled | revoked
    lastHeartbeatAt: timestamp("last_heartbeat_at"),
    ...updatedAndCreatedAt,
});

export const enrollmentTokenRelations = relations(enrollmentTokens, ({ one }) => ({
    creator: one(user, {
        fields: [enrollmentTokens.createdBy],
        references: [user.id],
    }),
    device: one(devices, {
        fields: [enrollmentTokens.deviceId],
        references: [devices.id],
    }),
}));

export const deviceRelations = relations(devices, ({ one }) => ({
    enrollmentToken: one(enrollmentTokens, {
        fields: [devices.enrollmentTokenId],
        references: [enrollmentTokens.id],
    }),
}));
