import { relations } from "drizzle-orm";
import { pgTable, text, timestamp, boolean, uuid, index, pgEnum } from "drizzle-orm/pg-core";
import { updatedAndCreatedAt } from "../timestampable";
import { integer } from "drizzle-orm/pg-core";

export const enrollementStatus = ["pending", "enrolled", "revoked", "unenrolled"] as const;
export const enrollementMethod = ["qr", "manual", "usb"] as const;
export const enrolmentStatusEnum = pgEnum("enrollement_status", enrollementStatus);
export const enrollementMethodEnum = pgEnum("enrollement_method", enrollementMethod);
/**
 * Single-use device enrollment token. Generated by an authenticated admin,
 * embedded (as an opaque secret) in the Device Owner provisioning QR and
 * consumed once by POST /api/v1/devices/enroll. Mono-tenant MVP: no tenant_id.
 */
export const enrollmentTokens = pgTable(
    "enrollment_tokens",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        token: text("token").notNull().unique(),
        expiresAt: timestamp("expires_at").notNull(),
        consumedAt: timestamp("consumed_at"),
        ...updatedAndCreatedAt,
    },
    (table) => [
        index("enrollment_token_idx").on(table.token),
    ],
);

export type EnrollmentTokenSqlInferSelect = typeof enrollmentTokens.$inferSelect;
export type EnrollmentTokenSqlInferInsert = typeof enrollmentTokens.$inferInsert;

/**
 * Single-use anti-replay nonce for the pinned-key enrollment handshake.
 * Fetched via GET /devices/enroll/challenge, then included (and signed) in
 * the canonical message the agent submits to POST /devices/enroll.
 */
export const enrollmentChallenges = pgTable(
    "enrollment_challenges",
    {
        id: uuid("id").primaryKey().defaultRandom(),
        challenge: text("challenge").notNull().unique(),
        expiresAt: timestamp("expires_at").notNull(),
        consumedAt: timestamp("consumed_at"),
        ...updatedAndCreatedAt,
    },
    (table) => [
        index("enrollment_challenge_idx").on(table.challenge),
    ],
);

export type EnrollmentChallengeSqlInferSelect = typeof enrollmentChallenges.$inferSelect;
export type EnrollmentChallengeSqlInferInsert = typeof enrollmentChallenges.$inferInsert;

/**
 * A device enrolled via a token. Holds the identity reported at enrollment and
 * is the `sub` of the long-lived device JWT (deviceToken).
 */
export const devices = pgTable("devices", {
    id: uuid("id").primaryKey().defaultRandom(),
    enrollmentId: uuid("enrollment_id").references(() => enrollmentTokens.id, { onDelete: "restrict" }).unique().notNull(),
    serial: text("serial"),
    androidId: text("android_id").unique(),
    model: text("model"),
    manufacturer: text("manufacturer"),
    osVersion: text("os_version"),
    imei: text("imei"),
    macAddress: text("mac_address"),
    ipAddress: text("ip_address"),
    enrollementStatus: enrolmentStatusEnum("enrollement_status").default("pending").notNull(),
    enrollementMethod: enrollementMethodEnum("enrollement_method").default("manual").notNull(),
    publicKey: text("public_key"),
    lastHeartbeatAt: timestamp("last_heartbeat_at"),
    //policyId: uuid("policy_id"),
    //groupId: uuid("group_id"),
    agentVersionCode: integer("agent_version_code"),
    agentVersionName: text("agent_version_name"),
    agentPackage: text("agent_package"),

    ...updatedAndCreatedAt,
},
    (table) => [
        index("enrollment_id_idx").on(table.enrollmentId),
    ],
);



export const deviceRelations = relations(devices, ({ one }) => ({
    enrollment: one(enrollmentTokens, {
        fields: [devices.enrollmentId],
        references: [enrollmentTokens.id],
    }),
}));
